class InfoMessage:
    userCreated = "User created successfully"
    retriveInfoSuccessfully = "Retrive user info successfully"
    loggedInSuccessfully = "Logged in successfully"
    weatherdatafetched = "Weather data fetched successfully"

class ErrorMessage:
    emailRequired = "Email is required"
    usernameRequired = "Username is required"
    usernameAlreadyExists = "Username already exists"
    userNotSaved = "User is not saved"
    emailRequired = "E-Mail is required"
    emailAlreadyExist = "E-Mail already exists."
    invalidPasswordFormat = "Password format is invalid"
    userNotFound = "User is not found"
    userInvalid = "user is invalid"
    invalidToken = "invalid token"
    genericError = "An error ocured when creating a new user"
    invalidEmailOrPassword = "Email or Password is invalid"
    somethingWentWrong = "Woops, something's quite wrong, please try again!"